name: E2E Test - Windows OS Release Builds

on:
  push:
    branches: [release-build-test-macos-trial]

jobs:
  e2e-test-macos-release-builds:
    name: E2E Test - Windows OS Release Builds
    # Only run this job if we're in the main repo, not a fork.
    if: github.repository == 'vmware-tanzu/community-edition'
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: E2E Test - Windows OS Release Builds
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_ACCESS_TOKEN }}
        run: |
          .\test\release-build-test\check-release-build.ps1 -version ${{ github.event.inputs.release_version }} -signToolPath "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\signtool.exe"
