name: E2E Test - MacOS and Linux OS Release Builds

on:
  push:
    branches: [release-build-test-macos-trial]

jobs:
  e2e-test-macos-release-builds:
    name: E2E Test - MacOS and Linux OS Release Builds
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: E2E Test - MacOS and Linux OS Release Builds
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_ACCESS_TOKEN }}
        run: |
          ./test/release-build-test/check-release-build.sh ${{ github.event.inputs.release_version }}
