name: E2E Test - Release Builds Trial 2

on:
  release:
    types:
      - unpublished

jobs:
  e2e-test-release-builds-trial-2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
        id: go

      - name: E2E Test - Release Builds
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
