name: E2E Test - Release Build Test for Windows - Trial

on:
  push:
    branches:
      - windows-release-build-test

jobs:
  e2e-release-build-test:
    # # Only run this job if we're in the main repo, not a fork.
    # if: github.repository == 'vmware-tanzu/community-edition'
    name: E2E Test - Release Build Test for Windows - Trial
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run E2E Tests
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop';
          $source = 'https://github.com/karuppiah7890/community-edition/releases/download/v0.51.9/tce-windows-amd64-v0.51.8.zip'
          $destination = 'tce-windows-amd64-v0.51.8.zip'
          Start-BitsTransfer -Source $source -Destination $destination
          Expand-Archive -LiteralPath tce-windows-amd64-v0.51.8.zip
          Get-ChildItem -Path "tce-windows-amd64-v0.51.8\tce-windows-amd64-v0.51.8\bin\tanzu-*" -File -Recurse | Foreach-Object {
            & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\signtool" verify /pa $_.FullName
            if ($LastExitCode -ne 0) {
              throw "Error verifying: " + $_.FullName
            }
          }
